info:
  name: baseline

data:
  path: /projects/users/data/UCPH/DeepFetal/projects/preterm/Data/AnyPreg_June_v3/train.parquet
  test_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/Data/OnlyFirstPreg_June_v3/test.parquet
  batch_size: 128
  val_frac: 0.05
  workers: 32
  ehr_data: []
  img_data: [physical_delta_x, physical_delta_y]
  img_size: [224, 224]
  oversample_ratio: 1 #0 = No oversampling
  label_smoothing_param: 2 #0 = No label smoothing

#remove / ignore / remove_on_GA 
#(Remove from DF if cond is true / ignore / remove if GA < GA_cutoff)
dataset: 
    progesterone: ignore 
    c-section: remove_on_GA
    induced: remove_on_GA

tasks:
  preterm:
    cutoffs: [34] #Sharp cutoff (GA < GA_cutoff)
    loss: 'bce'
    weights: [1]
  aux_tasks:
    - var: GA_weeks
      loss: 'l2'
      weights: 0.01

training:
  epochs: 60
  vit_frozen_until: 10  #VIT is frozen until this epoch
  ehr_frozen_until: 10 #EHR is frozen until this epoch
  #Unfreezeing strategy. Unfreeze blocks_per_step every_n_epochs until we reach top_n_blocks are unfrozen.
  #blocks_per_step = -1, top_n_blocks = -1 is all layers immediately
  #blocks_per_step = -1, top_n_blocks = N is top N layers immediately
  blocks_per_step: -1 
  every_n_epochs: 2
  top_n_blocks: -1
  
auxiliary:
  method: append

model:
  vit:
    type: vitb16
    #weights_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/other_models/weights/vitb16.pth #VitB
    weights_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/other_models/weights/oversampled_vitb16.pth 
    #weights_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/other_models/weights/oversampled_vitl16.pth 
    dropout: 0.2
  
  ehr:
    type: patient_lookup
    num_tokens: 3
     
  
  transform:
    layer_dims:
    - 16

  head:
    layer_dims: []
    dropout: 0.2
    
optimizer:
  type: AdamW
  lr1: 5e-4 #Used while ViT is frozen
  lr2: 5e-5 #Used while ViT is unfrozen
  lr_decay: 0.55
  weight_decay: 1e-2

  #AdamW
  adamw_params: [0.9,0.999, 1e-8] #Beta1, Beta2, Epsilon
  
scheduler:
  type: cosine_warmup
  num_warmup_steps: 10
  num_cycles: 1 #A multiplier for the cosine scheduler. 2 means two cycles over training
  
device:
  type: cuda
